# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('isAdmin', models.BooleanField()),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=300)),
                ('tel', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
    ]
