# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('sum_price', models.FloatField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.User')),
            ],
        ),
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_product', models.IntegerField()),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=20)),
                ('amount_product', models.IntegerField()),
                ('price_product', models.FloatField(max_length=5)),
                ('score_product', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.IntegerField(choices=[(1, 'Processing'), (2, 'Preparing'), (3, 'Delivering'), (4, 'Success')])),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Order')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.User')),
            ],
        ),
        migrations.AddField(
            model_name='order_list',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='list_product',
            field=models.ManyToManyField(through='store.Order_list', to='store.Product'),
        ),
    ]
