# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20161029_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_list',
            new_name='OrderList',
        ),
        migrations.AlterField(
            model_name='product',
            name='score_product',
            field=models.FloatField(),
        ),
    ]
